-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 03:19:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET latin1 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`carnet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`carnet` (
  `idCarnet` INT(11) NOT NULL,
  `cedula` VARCHAR(14) NULL DEFAULT NULL,
  `fecha_inscripcion` DATE NOT NULL,
  `fecha_espiracion` DATE NOT NULL,
  `tipo_Lector` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCarnet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`prestaciones` (
  `idPrestaciones` INT(11) NOT NULL,
  `Observacion` VARCHAR(100) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `FechaPrest` DATE NOT NULL,
  PRIMARY KEY (`idPrestaciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libros` (
  `idLibros` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `ibsn` INT(11) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `dificultad` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `cantStock` INT(11) NULL DEFAULT NULL,
  `prestaciones_idPrestaciones` INT(11) NOT NULL,
  PRIMARY KEY (`idLibros`),
  INDEX `fk_libros_prestaciones1_idx` (`prestaciones_idPrestaciones` ASC),
  CONSTRAINT `fk_libros_prestaciones1`
    FOREIGN KEY (`prestaciones_idPrestaciones`)
    REFERENCES `biblioteca`.`prestaciones` (`idPrestaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreUsu` VARCHAR(45) NOT NULL,
  `contraUsu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `nombreUsu_UNIQUE` (`nombreUsu` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`registro` (
  `idregistro` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(14) NOT NULL,
  `dni` VARCHAR(14) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `fecha` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `rol` CHAR(2) NULL DEFAULT 'n',
  `carnet_idCarnet` INT(11) NOT NULL,
  `usuarios_idUsuarios` INT(11) NOT NULL,
  PRIMARY KEY (`idregistro`, `carnet_idCarnet`, `usuarios_idUsuarios`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_registro_carnet_idx` (`carnet_idCarnet` ASC),
  INDEX `fk_registro_usuarios1_idx` (`usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_registro_carnet`
    FOREIGN KEY (`carnet_idCarnet`)
    REFERENCES `biblioteca`.`carnet` (`idCarnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_usuarios1`
    FOREIGN KEY (`usuarios_idUsuarios`)
    REFERENCES `biblioteca`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `biblioteca`.`registro_has_prestaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`registro_has_prestaciones` (
  `registro_idregistro` INT(11) NOT NULL,
  `registro_carnet_idCarnet` INT(11) NOT NULL,
  `registro_usuarios_idUsuarios` INT(11) NOT NULL,
  `prestaciones_idPrestaciones` INT(11) NOT NULL,
  PRIMARY KEY (`registro_idregistro`, `registro_carnet_idCarnet`, `registro_usuarios_idUsuarios`, `prestaciones_idPrestaciones`),
  INDEX `fk_registro_has_prestaciones_prestaciones1_idx` (`prestaciones_idPrestaciones` ASC),
  INDEX `fk_registro_has_prestaciones_registro1_idx` (`registro_idregistro` ASC, `registro_carnet_idCarnet` ASC, `registro_usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_registro_has_prestaciones_registro1`
    FOREIGN KEY (`registro_idregistro` , `registro_carnet_idCarnet` , `registro_usuarios_idUsuarios`)
    REFERENCES `biblioteca`.`registro` (`idregistro` , `carnet_idCarnet` , `usuarios_idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_has_prestaciones_prestaciones1`
    FOREIGN KEY (`prestaciones_idPrestaciones`)
    REFERENCES `biblioteca`.`prestaciones` (`idPrestaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
